channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.2
  - python=3.9.12
  - requests=2.27.1
  - matplotlib=3.5.2
  - jupyterlab=3.4.4
  - pip=22.1.2
  - pip:
    - oci==2.72.0
    - opencv-python==4.6.0.66
